// GENERATED by `npm run db:types` (supabase gen types typescript). Do not edit by hand.
// Regenerate after every migration and commit the result.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "app_settings": {
                  Row: {
                    "created_at": string,"key": string,"updated_at": string,"updated_by": string | null,"value": NonNullable<Json>
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"key": string,"updated_at"?: string,"updated_by"?: string | null,"value": NonNullable<Json>
                  }
                  Update: {
                    "created_at"?: string,"key"?: string,"updated_at"?: string,"updated_by"?: string | null,"value"?: NonNullable<Json>
                  }
                  Relationships: [
                    {
      foreignKeyName: "app_settings_updated_by_fkey"
      columns: ["updated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"audit_log": {
                  Row: {
                    "action": string,"actor_id": string | null,"after": Json | null,"before": Json | null,"created_at": string,"entity": string,"entity_id": string | null,"id": string,"ip": unknown
                  }
                  ComputedFields: never
                  Insert: {
                    "action": string,"actor_id"?: string | null,"after"?: Json | null,"before"?: Json | null,"created_at"?: string,"entity": string,"entity_id"?: string | null,"id"?: string,"ip"?: unknown
                  }
                  Update: {
                    "action"?: string,"actor_id"?: string | null,"after"?: Json | null,"before"?: Json | null,"created_at"?: string,"entity"?: string,"entity_id"?: string | null,"id"?: string,"ip"?: unknown
                  }
                  Relationships: [
                    {
      foreignKeyName: "audit_log_actor_id_fkey"
      columns: ["actor_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"grievances": {
                  Row: {
                    "admin_note": string | null,"category": string,"created_at": string,"email": string,"handled_by": string | null,"id": string,"message": string,"name": string,"reference": string,"resolved_at": string | null,"status": string,"subject": string,"updated_at": string,"user_id": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "admin_note"?: string | null,"category"?: string,"created_at"?: string,"email": string,"handled_by"?: string | null,"id"?: string,"message": string,"name": string,"reference"?: string,"resolved_at"?: string | null,"status"?: string,"subject": string,"updated_at"?: string,"user_id"?: string | null
                  }
                  Update: {
                    "admin_note"?: string | null,"category"?: string,"created_at"?: string,"email"?: string,"handled_by"?: string | null,"id"?: string,"message"?: string,"name"?: string,"reference"?: string,"resolved_at"?: string | null,"status"?: string,"subject"?: string,"updated_at"?: string,"user_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "grievances_handled_by_fkey"
      columns: ["handled_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "grievances_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ledger_entries": {
                  Row: {
                    "amount": number,"created_at": string,"id": string,"note": string | null,"ref_id": string | null,"type": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "amount": number,"created_at"?: string,"id"?: string,"note"?: string | null,"ref_id"?: string | null,"type": string,"user_id": string
                  }
                  Update: {
                    "amount"?: number,"created_at"?: string,"id"?: string,"note"?: string | null,"ref_id"?: string | null,"type"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ledger_entries_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "wallets"
      referencedColumns: ["user_id"]
    }
                  ]
                },"market_translations": {
                  Row: {
                    "created_at": string,"description": string,"id": string,"locale": string,"market_id": string,"reviewed_by": string | null,"source_hash": string,"status": string,"title": string,"translated_at": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"description"?: string,"id"?: string,"locale": string,"market_id": string,"reviewed_by"?: string | null,"source_hash": string,"status"?: string,"title": string,"translated_at"?: string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"description"?: string,"id"?: string,"locale"?: string,"market_id"?: string,"reviewed_by"?: string | null,"source_hash"?: string,"status"?: string,"title"?: string,"translated_at"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "market_translations_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "market_translations_reviewed_by_fkey"
      columns: ["reviewed_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"markets": {
                  Row: {
                    "category": string,"created_at": string,"created_by": string | null,"description": string,"end_date": string,"id": string,"is_binary": boolean,"is_featured": boolean,"is_live": boolean,"legacy_id": string | null,"liquidity_b": number,"region": string,"resolution_source": string,"resolved_at": string | null,"resolved_outcome_id": string | null,"slug": string,"status": string,"subcategory": string,"tags": (string)[],"title": string,"total_volume": number,"updated_at": string,"volume_change_24h": number
                  }
                  ComputedFields: never
                  Insert: {
                    "category": string,"created_at"?: string,"created_by"?: string | null,"description"?: string,"end_date": string,"id"?: string,"is_binary"?: boolean,"is_featured"?: boolean,"is_live"?: boolean,"legacy_id"?: string | null,"liquidity_b"?: number,"region"?: string,"resolution_source"?: string,"resolved_at"?: string | null,"resolved_outcome_id"?: string | null,"slug": string,"status"?: string,"subcategory": string,"tags"?: (string)[],"title": string,"total_volume"?: number,"updated_at"?: string,"volume_change_24h"?: number
                  }
                  Update: {
                    "category"?: string,"created_at"?: string,"created_by"?: string | null,"description"?: string,"end_date"?: string,"id"?: string,"is_binary"?: boolean,"is_featured"?: boolean,"is_live"?: boolean,"legacy_id"?: string | null,"liquidity_b"?: number,"region"?: string,"resolution_source"?: string,"resolved_at"?: string | null,"resolved_outcome_id"?: string | null,"slug"?: string,"status"?: string,"subcategory"?: string,"tags"?: (string)[],"title"?: string,"total_volume"?: number,"updated_at"?: string,"volume_change_24h"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "markets_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "markets_resolved_outcome_fk"
      columns: ["resolved_outcome_id","id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    }
                  ]
                },"orders": {
                  Row: {
                    "amount": number,"avg_price": number,"created_at": string,"id": string,"idempotency_key": string,"market_id": string,"outcome_id": string,"shares": number,"side": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "amount": number,"avg_price": number,"created_at"?: string,"id"?: string,"idempotency_key": string,"market_id": string,"outcome_id": string,"shares": number,"side"?: string,"user_id": string
                  }
                  Update: {
                    "amount"?: number,"avg_price"?: number,"created_at"?: string,"id"?: string,"idempotency_key"?: string,"market_id"?: string,"outcome_id"?: string,"shares"?: number,"side"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "orders_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "orders_outcome_id_market_id_fkey"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    },{
      foreignKeyName: "orders_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"outcome_translations": {
                  Row: {
                    "created_at": string,"id": string,"label": string,"locale": string,"outcome_id": string,"source_hash": string,"status": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"id"?: string,"label": string,"locale": string,"outcome_id": string,"source_hash": string,"status"?: string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"label"?: string,"locale"?: string,"outcome_id"?: string,"source_hash"?: string,"status"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "outcome_translations_outcome_id_fkey"
      columns: ["outcome_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id"]
    }
                  ]
                },"outcomes": {
                  Row: {
                    "created_at": string,"id": string,"label": string,"legacy_key": string | null,"market_id": string,"price": number,"shares_outstanding": number,"sort_order": number,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"id"?: string,"label": string,"legacy_key"?: string | null,"market_id": string,"price": number,"shares_outstanding"?: number,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"label"?: string,"legacy_key"?: string | null,"market_id"?: string,"price"?: number,"shares_outstanding"?: number,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "outcomes_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    }
                  ]
                },"positions": {
                  Row: {
                    "avg_price": number,"created_at": string,"id": string,"market_id": string,"outcome_id": string,"realized_pnl": number,"resolved": boolean,"shares": number,"updated_at": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "avg_price"?: number,"created_at"?: string,"id"?: string,"market_id": string,"outcome_id": string,"realized_pnl"?: number,"resolved"?: boolean,"shares"?: number,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "avg_price"?: number,"created_at"?: string,"id"?: string,"market_id"?: string,"outcome_id"?: string,"realized_pnl"?: number,"resolved"?: boolean,"shares"?: number,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "positions_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "positions_outcome_id_market_id_fkey"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    },{
      foreignKeyName: "positions_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"price_history": {
                  Row: {
                    "at": string,"id": string,"market_id": string,"outcome_id": string,"price": number,"volume": number
                  }
                  ComputedFields: never
                  Insert: {
                    "at"?: string,"id"?: string,"market_id": string,"outcome_id": string,"price": number,"volume"?: number
                  }
                  Update: {
                    "at"?: string,"id"?: string,"market_id"?: string,"outcome_id"?: string,"price"?: number,"volume"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "price_history_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "price_history_outcome_id_market_id_fkey"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "age_confirmed_at": string | null,"created_at": string,"daily_trade_limit": number | null,"display_name": string | null,"handle": string,"id": string,"language": string,"role": string,"status": string,"suspended_at": string | null,"suspended_reason": string | null,"terms_version": string | null,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "age_confirmed_at"?: string | null,"created_at"?: string,"daily_trade_limit"?: number | null,"display_name"?: string | null,"handle": string,"id": string,"language"?: string,"role"?: string,"status"?: string,"suspended_at"?: string | null,"suspended_reason"?: string | null,"terms_version"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "age_confirmed_at"?: string | null,"created_at"?: string,"daily_trade_limit"?: number | null,"display_name"?: string | null,"handle"?: string,"id"?: string,"language"?: string,"role"?: string,"status"?: string,"suspended_at"?: string | null,"suspended_reason"?: string | null,"terms_version"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"rate_limits": {
                  Row: {
                    "bucket": string,"hits": number,"key_hash": string,"window_start": string
                  }
                  ComputedFields: never
                  Insert: {
                    "bucket": string,"hits"?: number,"key_hash": string,"window_start": string
                  }
                  Update: {
                    "bucket"?: string,"hits"?: number,"key_hash"?: string,"window_start"?: string
                  }
                  Relationships: [
                    
                  ]
                },"resolution_proposals": {
                  Row: {
                    "approved_at": string | null,"approved_by": string | null,"created_at": string,"decided_at": string | null,"decided_by": string | null,"decided_reason": string | null,"dispute_ends_at": string | null,"evidence_url": string,"finalized_at": string | null,"id": string,"kind": string,"market_id": string,"note": string,"outcome_id": string | null,"proposed_at": string,"proposed_by": string | null,"self_approved": boolean,"status": string,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "approved_at"?: string | null,"approved_by"?: string | null,"created_at"?: string,"decided_at"?: string | null,"decided_by"?: string | null,"decided_reason"?: string | null,"dispute_ends_at"?: string | null,"evidence_url": string,"finalized_at"?: string | null,"id"?: string,"kind": string,"market_id": string,"note": string,"outcome_id"?: string | null,"proposed_at"?: string,"proposed_by"?: string | null,"self_approved"?: boolean,"status"?: string,"updated_at"?: string
                  }
                  Update: {
                    "approved_at"?: string | null,"approved_by"?: string | null,"created_at"?: string,"decided_at"?: string | null,"decided_by"?: string | null,"decided_reason"?: string | null,"dispute_ends_at"?: string | null,"evidence_url"?: string,"finalized_at"?: string | null,"id"?: string,"kind"?: string,"market_id"?: string,"note"?: string,"outcome_id"?: string | null,"proposed_at"?: string,"proposed_by"?: string | null,"self_approved"?: boolean,"status"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "resolution_outcome_in_market"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    },{
      foreignKeyName: "resolution_proposals_approved_by_fkey"
      columns: ["approved_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "resolution_proposals_decided_by_fkey"
      columns: ["decided_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "resolution_proposals_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "resolution_proposals_proposed_by_fkey"
      columns: ["proposed_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"wallets": {
                  Row: {
                    "balance": number,"created_at": string,"updated_at": string,"user_id": string
                  }
                  ComputedFields: never
                  Insert: {
                    "balance"?: number,"created_at"?: string,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "balance"?: number,"created_at"?: string,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "wallets_user_id_fkey"
      columns: ["user_id"]
isOneToOne: true
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "_audit":
{ Args: { "p_action": string,"p_actor": string,"p_after": Json,"p_before": Json,"p_entity": string,"p_entity_id": string }; Returns: undefined
                           },
"_confirm":
{ Args: { "p_slug": string,"p_typed": string }; Returns: undefined
                           },
"_market_json":
{ Args: { "p_id": string }; Returns: Json
                           },
"_outcome_labels":
{ Args: { "p": Json,"p_is_binary": boolean }; Returns: (string)[]
                           },
"_replace_outcomes":
{ Args: { "p_labels": (string)[],"p_market": string }; Returns: undefined
                           },
"_setting":
{ Args: { "p_key": string }; Returns: Json
                           },
"_settle":
{ Args: { "p_actor": string,"p_proposal_id": string }; Returns: Json
                           },
"_staff":
{ Args: { "p_min_role": string }; Returns: {
              "age_confirmed_at": string | null,
"created_at": string,
"daily_trade_limit": number | null,
"display_name": string | null,
"handle": string,
"id": string,
"language": string,
"role": string,
"status": string,
"suspended_at": string | null,
"suspended_reason": string | null,
"terms_version": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "profiles"
        isOneToOne: true
        isSetofReturn: false
      } },
"admin_adjust_credits":
{ Args: { "p_amount": number,"p_reason": string,"p_user_id": string }; Returns: number
                           },
"admin_close_market":
{ Args: { "p_confirm_slug": string,"p_market_id": string }; Returns: undefined
                           },
"admin_create_market":
{ Args: { "p": Json }; Returns: string
                           },
"admin_grant_by_email":
{ Args: { "p_email": string }; Returns: string
                           },
"admin_publish_market":
{ Args: { "p_confirm_slug": string,"p_market_id": string }; Returns: undefined
                           },
"admin_set_role":
{ Args: { "p_role": string,"p_user_id": string }; Returns: undefined
                           },
"admin_set_user_status":
{ Args: { "p_reason": string,"p_status": string,"p_user_id": string }; Returns: undefined
                           },
"admin_update_grievance":
{ Args: { "p_id": string,"p_note": string,"p_status": string }; Returns: undefined
                           },
"admin_update_market":
{ Args: { "p": Json,"p_market_id": string }; Returns: undefined
                           },
"admin_update_setting":
{ Args: { "p_key": string,"p_value": Json }; Returns: undefined
                           },
"approve_resolution":
{ Args: { "p_confirm_slug": string,"p_proposal_id": string }; Returns: string
                           },
"confirm_age":
{ Args: { "p_terms_version": string }; Returns: string
                           },
"finalize_resolution":
{ Args: { "p_confirm_slug": string,"p_proposal_id": string }; Returns: Json
                           },
"hit_rate_limit":
{ Args: { "p_bucket": string,"p_key_hash": string,"p_limit": number,"p_window_seconds": number }; Returns: boolean
                           },
"lmsr_lse":
{ Args: { "b": number,"q": (number)[] }; Returns: number
                           },
"lmsr_prices":
{ Args: { "b": number,"q": (number)[] }; Returns: (number)[]
                           },
"lmsr_shares_for_amount":
{ Args: { "amount": number,"b": number,"i": number,"q": (number)[] }; Returns: number
                           },
"market_volume_24h":
{ Args: Record<PropertyKey, never>; Returns: {
              "market_id": string,"volume": number
            }[]
                           },
"outcome_prices_24h_ago":
{ Args: Record<PropertyKey, never>; Returns: {
              "outcome_id": string,"price": number
            }[]
                           },
"place_order":
{ Args: { "p_amount": number,"p_idempotency_key": string,"p_market_id": string,"p_outcome_id": string }; Returns: Json
                           },
"propose_resolution":
{ Args: { "p_evidence_url": string,"p_market_id": string,"p_note": string,"p_outcome_id": string }; Returns: string
                           },
"reject_resolution":
{ Args: { "p_proposal_id": string,"p_reason": string }; Returns: undefined
                           },
"run_scheduled_jobs":
{ Args: Record<PropertyKey, never>; Returns: Json
                           },
"unique_handle":
{ Args: { "p_email": string }; Returns: string
                           }
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            
          }
        }
} as const
