// GENERATED by `npm run db:types` (supabase gen types typescript). Do not edit by hand.
// Regenerate after every migration and commit the result.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "app_settings": {
                  Row: {
                    "created_at": string,"key": string,"updated_at": string,"updated_by": string | null,"value": NonNullable<Json>
                  }
                  Insert: {
                    "created_at"?: string,"key": string,"updated_at"?: string,"updated_by"?: string | null,"value": NonNullable<Json>
                  }
                  Update: {
                    "created_at"?: string,"key"?: string,"updated_at"?: string,"updated_by"?: string | null,"value"?: NonNullable<Json>
                  }
                  Relationships: [
                    {
      foreignKeyName: "app_settings_updated_by_fkey"
      columns: ["updated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"audit_log": {
                  Row: {
                    "action": string,"actor_id": string | null,"after": Json | null,"before": Json | null,"created_at": string,"entity": string,"entity_id": string | null,"id": string,"ip": unknown
                  }
                  Insert: {
                    "action": string,"actor_id"?: string | null,"after"?: Json | null,"before"?: Json | null,"created_at"?: string,"entity": string,"entity_id"?: string | null,"id"?: string,"ip"?: unknown
                  }
                  Update: {
                    "action"?: string,"actor_id"?: string | null,"after"?: Json | null,"before"?: Json | null,"created_at"?: string,"entity"?: string,"entity_id"?: string | null,"id"?: string,"ip"?: unknown
                  }
                  Relationships: [
                    {
      foreignKeyName: "audit_log_actor_id_fkey"
      columns: ["actor_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"grievances": {
                  Row: {
                    "created_at": string,"email": string,"id": string,"message": string,"name": string,"status": string,"subject": string,"updated_at": string,"user_id": string | null
                  }
                  Insert: {
                    "created_at"?: string,"email": string,"id"?: string,"message": string,"name": string,"status"?: string,"subject": string,"updated_at"?: string,"user_id"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"email"?: string,"id"?: string,"message"?: string,"name"?: string,"status"?: string,"subject"?: string,"updated_at"?: string,"user_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "grievances_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"ledger_entries": {
                  Row: {
                    "amount": number,"created_at": string,"id": string,"note": string | null,"ref_id": string | null,"type": string,"user_id": string
                  }
                  Insert: {
                    "amount": number,"created_at"?: string,"id"?: string,"note"?: string | null,"ref_id"?: string | null,"type": string,"user_id": string
                  }
                  Update: {
                    "amount"?: number,"created_at"?: string,"id"?: string,"note"?: string | null,"ref_id"?: string | null,"type"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ledger_entries_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "wallets"
      referencedColumns: ["user_id"]
    }
                  ]
                },"market_translations": {
                  Row: {
                    "created_at": string,"description": string,"id": string,"locale": string,"market_id": string,"reviewed_by": string | null,"source_hash": string,"status": string,"title": string,"translated_at": string,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"description"?: string,"id"?: string,"locale": string,"market_id": string,"reviewed_by"?: string | null,"source_hash": string,"status"?: string,"title": string,"translated_at"?: string,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"description"?: string,"id"?: string,"locale"?: string,"market_id"?: string,"reviewed_by"?: string | null,"source_hash"?: string,"status"?: string,"title"?: string,"translated_at"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "market_translations_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "market_translations_reviewed_by_fkey"
      columns: ["reviewed_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"markets": {
                  Row: {
                    "category": string,"created_at": string,"created_by": string | null,"description": string,"end_date": string,"id": string,"is_binary": boolean,"is_featured": boolean,"is_live": boolean,"legacy_id": string | null,"liquidity_b": number,"resolution_source": string,"resolved_at": string | null,"resolved_outcome_id": string | null,"slug": string,"status": string,"subcategory": string,"title": string,"total_volume": number,"updated_at": string,"volume_change_24h": number
                  }
                  Insert: {
                    "category": string,"created_at"?: string,"created_by"?: string | null,"description"?: string,"end_date": string,"id"?: string,"is_binary"?: boolean,"is_featured"?: boolean,"is_live"?: boolean,"legacy_id"?: string | null,"liquidity_b"?: number,"resolution_source"?: string,"resolved_at"?: string | null,"resolved_outcome_id"?: string | null,"slug": string,"status"?: string,"subcategory": string,"title": string,"total_volume"?: number,"updated_at"?: string,"volume_change_24h"?: number
                  }
                  Update: {
                    "category"?: string,"created_at"?: string,"created_by"?: string | null,"description"?: string,"end_date"?: string,"id"?: string,"is_binary"?: boolean,"is_featured"?: boolean,"is_live"?: boolean,"legacy_id"?: string | null,"liquidity_b"?: number,"resolution_source"?: string,"resolved_at"?: string | null,"resolved_outcome_id"?: string | null,"slug"?: string,"status"?: string,"subcategory"?: string,"title"?: string,"total_volume"?: number,"updated_at"?: string,"volume_change_24h"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "markets_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "markets_resolved_outcome_fk"
      columns: ["resolved_outcome_id","id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    }
                  ]
                },"orders": {
                  Row: {
                    "amount": number,"avg_price": number,"created_at": string,"id": string,"idempotency_key": string,"market_id": string,"outcome_id": string,"shares": number,"side": string,"user_id": string
                  }
                  Insert: {
                    "amount": number,"avg_price": number,"created_at"?: string,"id"?: string,"idempotency_key": string,"market_id": string,"outcome_id": string,"shares": number,"side"?: string,"user_id": string
                  }
                  Update: {
                    "amount"?: number,"avg_price"?: number,"created_at"?: string,"id"?: string,"idempotency_key"?: string,"market_id"?: string,"outcome_id"?: string,"shares"?: number,"side"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "orders_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "orders_outcome_id_market_id_fkey"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    },{
      foreignKeyName: "orders_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"outcomes": {
                  Row: {
                    "created_at": string,"id": string,"label": string,"legacy_key": string | null,"market_id": string,"price": number,"shares_outstanding": number,"sort_order": number,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"label": string,"legacy_key"?: string | null,"market_id": string,"price": number,"shares_outstanding"?: number,"sort_order"?: number,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"label"?: string,"legacy_key"?: string | null,"market_id"?: string,"price"?: number,"shares_outstanding"?: number,"sort_order"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "outcomes_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    }
                  ]
                },"positions": {
                  Row: {
                    "avg_price": number,"created_at": string,"id": string,"market_id": string,"outcome_id": string,"realized_pnl": number,"resolved": boolean,"shares": number,"updated_at": string,"user_id": string
                  }
                  Insert: {
                    "avg_price"?: number,"created_at"?: string,"id"?: string,"market_id": string,"outcome_id": string,"realized_pnl"?: number,"resolved"?: boolean,"shares"?: number,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "avg_price"?: number,"created_at"?: string,"id"?: string,"market_id"?: string,"outcome_id"?: string,"realized_pnl"?: number,"resolved"?: boolean,"shares"?: number,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "positions_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "positions_outcome_id_market_id_fkey"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    },{
      foreignKeyName: "positions_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"price_history": {
                  Row: {
                    "at": string,"id": string,"market_id": string,"outcome_id": string,"price": number,"volume": number
                  }
                  Insert: {
                    "at"?: string,"id"?: string,"market_id": string,"outcome_id": string,"price": number,"volume"?: number
                  }
                  Update: {
                    "at"?: string,"id"?: string,"market_id"?: string,"outcome_id"?: string,"price"?: number,"volume"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "price_history_market_id_fkey"
      columns: ["market_id"]
isOneToOne: false
      referencedRelation: "markets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "price_history_outcome_id_market_id_fkey"
      columns: ["outcome_id","market_id"]
isOneToOne: false
      referencedRelation: "outcomes"
      referencedColumns: ["id","market_id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "age_confirmed_at": string | null,"created_at": string,"display_name": string | null,"handle": string,"id": string,"language": string,"role": string,"status": string,"terms_version": string | null,"updated_at": string
                  }
                  Insert: {
                    "age_confirmed_at"?: string | null,"created_at"?: string,"display_name"?: string | null,"handle": string,"id": string,"language"?: string,"role"?: string,"status"?: string,"terms_version"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "age_confirmed_at"?: string | null,"created_at"?: string,"display_name"?: string | null,"handle"?: string,"id"?: string,"language"?: string,"role"?: string,"status"?: string,"terms_version"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"wallets": {
                  Row: {
                    "balance": number,"created_at": string,"updated_at": string,"user_id": string
                  }
                  Insert: {
                    "balance"?: number,"created_at"?: string,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "balance"?: number,"created_at"?: string,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "wallets_user_id_fkey"
      columns: ["user_id"]
isOneToOne: true
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            [_ in never]: never
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            
          }
        }
} as const
